[package]
name = "evaluation"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "evaluate"
path = "src/bin/evaluate.rs"
required-features = ["full"]

[[bin]]
name = "eval-export"
path = "src/bin/export.rs"

[[bin]]
name = "component-eval"
path = "src/bin/component_eval.rs"
required-features = ["full"]

[[bin]]
name = "infra-bench"
path = "src/bin/infra_bench.rs"

[[bin]]
name = "infra-eval"
path = "src/bin/infra_eval.rs"

[features]
default = []
input = []
oracle = []
guidance = []
full = ["input", "oracle", "guidance"]
build-bench = ["build"]

[dependencies]
controller = { path = "../controller" }
automutate-common = { path = "../common" }
build = { path = "../build", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true
tokio = { workspace = true, features = ["full"] }
