[package]
name = "worker-agent"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tonic.workspace = true
prost.workspace = true
tonic-prost = "0.14.2"
tonic-reflection = "0.14.2"
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
thiserror.workspace = true
async-stream = "0.3.6"
tokio-stream = "0.1.17"

[build-dependencies]
tonic-prost-build = "0.14.2"
